services:
  web-angular:
    build: .
    container_name: angular-nginx-app
    ports:
      - "8080:80" # Acceder√°s en localhost:8080
    networks:
      - mi-red-app

networks:
  mi-red-app:
    driver: bridge